import org.openqa.selenium.support.ui.Select;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.ArrayList;
import io.appium.java_client.android.nativekey.AndroidKey;
import io.appium.java_client.android.nativekey.KeyEvent;
import java.time.MonthDay;
import org.testng.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;
import java.time.Duration;
import java.util.List;
import java.util.Random;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.*;
import org.openqa.selenium.html5.Location;
import io.appium.java_client.android.AndroidDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.Point;
import org.openqa.selenium.interactions.PointerInput;
import org.openqa.selenium.interactions.Sequence;
import org.openqa.selenium.interactions.Pause;
import java.time.Duration;
import static org.openqa.selenium.interactions.PointerInput.Kind.TOUCH;
import static org.openqa.selenium.interactions.PointerInput.Origin.viewport;
import static org.openqa.selenium.interactions.PointerInput.MouseButton.LEFT;
import io.testgrid.listeners.TestListener;
import io.testgrid.listeners.RetryFailedTestCases;
import io.testgrid.tg;
import org.testng.annotations.*;
import app.getxray.xray.testng.annotations.XrayTest;
import io.testgrid.enums.ComparisonType;
import org.json.JSONObject;
import io.testgrid.enums.Direction;
import io.testgrid.enums.Size;
import io.testgrid.enums.Buttons;
import static io.testgrid.baseClass.driver;
import org.openqa.selenium.*;
import io.testgrid.enums.Alert;
import io.appium.java_client.android.AndroidDriver;
import io.appium.java_client.ios.IOSDriver;
import org.testng.annotations.Test;

class fndigitaltlifeandroidswitchdeliverytogroundandback {

	public static void fndigitaltlifeandroidswitchdeliverytogroundandback() {
		tg.scroll("ele_tlifeAnDeliveryMethodEditButton", Direction.DOWN);
		tg.wait("ele_tlifeAnDeliveryMethodEditButton", ComparisonType.IS_VISIBLE);
		tg.click("ele_tlifeAnDeliveryMethodEditButton", 1);
		tg.wait("ele_tlifeAnDeliveryGround", ComparisonType.IS_VISIBLE);
		tg.click("ele_tlifeAnDeliveryGround", 1);
		tg.wait(2);
		START_CUSTOM_SCRIPT;
		          PointerInput finger1 = new PointerInput(PointerInput.Kind.TOUCH, "finger1");
		          Sequence tap1 = new Sequence(finger1, 1);
		          tap1.addAction(finger1.createPointerMove(Duration.ZERO, PointerInput.Origin.viewport(), 540, 2000));
		          tap1.addAction(finger1.createPointerDown(PointerInput.MouseButton.LEFT.asArg()));
		          tap1.addAction(finger1.createPointerUp(PointerInput.MouseButton.LEFT.asArg()));
		          driver.perform(java.util.Arrays.asList(tap1));
		END_CUSTOM_SCRIPT;
		tg.wait(5);
		// [DISABLED] tg.wait("ele_tlifeAnDeliveryTypeGround", ComparisonType.IS_VISIBLE, 20);
		tg.scroll("ele_tlifeAnDeliveryMethodEditButton", Direction.DOWN);
		tg.wait("ele_tlifeAnDeliveryMethodEditButton", ComparisonType.IS_VISIBLE);
		tg.click("ele_tlifeAnDeliveryMethodEditButton", 1);
		tg.wait("ele_tlifeAnDeliveryTwoDay", ComparisonType.IS_VISIBLE);
		tg.click("ele_tlifeAnDeliveryTwoDay", 1);
		tg.wait(2);
		START_CUSTOM_SCRIPT;
		          PointerInput finger2 = new PointerInput(PointerInput.Kind.TOUCH, "finger2");
		          Sequence tap2 = new Sequence(finger2, 1);
		          tap2.addAction(finger2.createPointerMove(Duration.ZERO, PointerInput.Origin.viewport(), 540, 2000));
		          tap2.addAction(finger2.createPointerDown(PointerInput.MouseButton.LEFT.asArg()));
		          tap2.addAction(finger2.createPointerUp(PointerInput.MouseButton.LEFT.asArg()));
		          driver.perform(java.util.Arrays.asList(tap2));
		END_CUSTOM_SCRIPT;
		tg.wait(5);
		tg.wait("ele_tlifeAnDeliveryTwoDay", ComparisonType.IS_VISIBLE, 20);
	}
}