public class constants {
	public static int var_count = 5;
	public static String var_TLifeUserName = "7188648059";
	public static String var_TLifePassword = "MagentaTest2026!";
	public static String var_CC_Prod_Name = "W2bnNIX3yy9u4wBjFAGVTEl/me0QmkVBfzMnmGylutc=:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_CC_Prod_Number = "Vwb+o1AxvPj5Epm8kXeQU2WjcjlW2JkMb2NXuZ2tfPY=:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_CC_Prod_Exp = "vE70OZVYgwPXlm1szEm04Q==:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_CC_Prod_CVV = "e32PkIF1vJKRdjlEfJt31g==:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_CC_Prod_Zipcode = "3fkdqo8zA8jWUTRp8jvN/A==:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_BundleID_Prod = "com.tmobile.tuesdays";
	public static String var_Bank_Prod_Account_Name = "John Trivolta";
	public static String var_Bank_Prod_Account_Number = "12345678";
	public static String var_Bank_Prod_Routing_Number = "051000017";
	public static String var_Username = "4255045541";
	public static String var_DeviceName = "Galaxy S26 Ultra";
	public static String var_Password = "MagentaTest2026!";
	public static String var_PhoneNumber = "4048672642";
	public static int var_sdfd = 23344;
	public static String var_Prod_UserName = "7188648059";
	public static String var_FirstDeviceName = "(//android.widget.TextView[@resource-id=\"device_name\"])[1]\'";
	public static String var_Select_Environment = "Staging";
	public static String var_SDDAdress1151 = "1403 NW Sammamish Rd";
	public static String var_Savingsvalue = "null";
	public static String var_deviceColor = "null";
	public static String var_Device_Name = "null";
	public static String var_TradeInIMEI = "353629306900878";
	public static String var_PlanName = "Experience More";
	public static String var_TG_copy_Exp = "mQB1zQLWJclvb+qqjkkZRQ==:MTIzNDU2Nzg5MTAxMTEyMQ==";
	public static String var_AccessoryName = "Accessory";
	public static String var_HSI_EligibleAddress = "null";
	public static int var_removeHowManyLines = 3;
	public static String var_Protection_Plan = "Protection 360";
	public static String var_Accessory_Name = "Apple";
	public static String var_DeviceStorage = "null";
	public static String var_tradeinvalue = "null";
	public static String var_bowisStoreLocation = "null";
	public static String var_bowisLocationOnPopUp = "null";
	public static String var_PortinNumber = "null";
	public static String var_SyncupIMEINumber = "null";
	public static String var_SyncupICCIDNumber = "null";
	public static String var_Environment = "Prodgreen";
	public static String var_HSI_Address = "null";
	public static String var_qlabEnv = "Qlab02";
	public static String var_IMEINumber = "985412365874417";
	public static String var_EIDNumber = "89049032006008882600112598684628";
	public static String var_IneligibleHSIAddress = "null";
	public static int var_NumberOfLinesRequired = 3;
	public static String var_HSI_Eligible_Business_Address = "1700 Crystal Dr, Arlington";
	public static String var_HSI_Eligible_Residential_Address = "3202 STRATFORD GREEN CT, AVONDALE ESTATES, GA 30002";
	public static String var_HSI_InEligible_Address = "12040 Juvenile St, Greenfield, OH 45123";
	public static String var_PersonalInfo_FirstName = "Loopback";
	public static String var_PersonalInfo_LastName = "Back";
	public static String var_PersonalInfo_DOB = "12281991";
	public static String var_PersonalInfo_SSN = "0005";
	public static String var_PersonalInfo_PhoneNo = "9910002000";
	public static String var_PersonalInfo_Email = "loopbacktest@gmail.com";
	public static String var_PersonalInfo_Address = "1 Ravinia Dr, Atlanta, GA 30346";
	public static String var_HSI_Eligible_Capped_Nomad_Address = "744 COALFIRE AVE BESSEMER AL 35023";
	public static String var_HIS_Eligible_OnlyAway_Address = "157 REBECCA DR GARDENDALE AL 35071";
	public static String var_Not_Eligible_Address_Plan = "91 Christopher Dr South Shore KY 41175";
	public static String var_latitude = "47.552008";
	public static String var_longitude = "-122.057529";
	public static String var_altitude = "0";
	public static String var_Fiber_plan_name = "fiber plan";
	public static String var_BASEIMEI = "35693803564380";
	public static Double var_ADDADP = 24.00;
	public static String var_SDD_Address = "1403 NW Sammamish Rd";
	public static int var_LineNumber = 1;
	public static String var_TLifeUserName01_Hermes = "4706620025";
	public static String var_TLifePassword01_Hermes = "Test123456@#$";
	public static String var_PackageName = "com.tmobile.tuesdays";
}